import { ClerkProvider } from "@clerk/nextjs";
import "~/styles/globals.css";
import { type Metadata } from "next";
import { Geist } from "next/font/google";
import { Topnav } from "./componets/topnav";

export const metadata: Metadata = {
  title: "Kain Tayo!",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/cooking.png" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
    <html lang="en" className={`${geist.variable}`}>
      <body>
      <Topnav/>
      {children}
      </body>
    </html>
    </ClerkProvider>
  );
}
